// Hand-written compatibility shim: not generated by ogen, not touched by `go generate ./...`.
package management_api

import "context"

// Deprecated: use DeleteAPIApplicationScopeOperation. Kept for source
// compatibility with the pre-typo-fix operation name.
const DeleteAPIAppliationScopeOperation = DeleteAPIApplicationScopeOperation

// Deprecated: use DeleteAPIApplicationScopeParams.
type DeleteAPIAppliationScopeParams = DeleteAPIApplicationScopeParams

// Deprecated: use DeleteAPIApplicationScopeRes.
type DeleteAPIAppliationScopeRes = DeleteAPIApplicationScopeRes

// Deprecated: use DeleteAPIApplicationScopeOK.
type DeleteAPIAppliationScopeOK = DeleteAPIApplicationScopeOK

// Deprecated: use DeleteAPIApplicationScopeBadRequest.
type DeleteAPIAppliationScopeBadRequest = DeleteAPIApplicationScopeBadRequest

// Deprecated: use DeleteAPIApplicationScopeForbidden.
type DeleteAPIAppliationScopeForbidden = DeleteAPIApplicationScopeForbidden

// Deprecated: use DeleteAPIApplicationScopeTooManyRequests.
type DeleteAPIAppliationScopeTooManyRequests = DeleteAPIApplicationScopeTooManyRequests

// DeleteAPIAppliationScope invokes DeleteAPIApplicationScope operation.
//
// Deprecated: use DeleteAPIApplicationScope.
func (c *Client) DeleteAPIAppliationScope(ctx context.Context, params DeleteAPIAppliationScopeParams) (DeleteAPIAppliationScopeRes, error) {
	return c.DeleteAPIApplicationScope(ctx, params)
}
